Реализация V2 и V3
PetrKopyev/simbirsoft-practice pull request #3
Opened 2022-02-20 19:48 UTC by PetrKopyev

2022-02-22 15:48 UTC, e3Y6 requested changes
Добавлены комментарии.

2022-02-22 15:48 UTC, e3Y6 commented on src/components/Stages.vue
> +      :key="stepIndex"
Индекс лучше не использовать в качестве ключа.

2022-02-22 15:48 UTC, e3Y6 commented on src/components/order/Model.vue
> +          alt=""
Пустой атрибут. Лучше добавить текст.

2022-02-22 15:48 UTC, e3Y6 commented on src/components/order/Model.vue
> +          alt=""
Пустой атрибут. Лучше добавить текст.

2022-02-22 15:48 UTC, e3Y6 commented on src/components/order/Model.vue
> +          alt=""
Пустой атрибут. Лучше добавить текст.

2022-02-28 08:43 UTC, PetrKopyev commented on src/components/SideOrderMenu.vue
> +    priceLabel() {
Учту когда буду выполнять задание по функционалу

2022-02-28 08:54 UTC, PetrKopyev commented on src/components/Stages.vue
> +      :key="stepIndex"
У меня не массив, а объект
И в качестве уникального ключа в цикле тут идёт свойство объекта

2022-02-28 09:25 UTC, PetrKopyev commented on src/components/SideOrderMenu.vue
> +      switch (this.selectedStep.code) {
исполнено

2022-02-28 09:26 UTC, PetrKopyev commented on src/components/order/Location.vue
> +          alt=""
done

2022-02-28 09:27 UTC, PetrKopyev commented on src/components/order/Model.vue
> +          alt=""
done

2022-02-28 09:27 UTC, PetrKopyev commented on src/components/order/Model.vue
> +          alt=""
done

2022-02-28 09:27 UTC, PetrKopyev commented on src/components/order/Model.vue
> +          alt=""
done

2022-02-28 09:33 UTC, PetrKopyev commented on src/components/SideOrderMenu.vue
> +        'side-order-menu__button',
done

2022-02-28 09:48 UTC, PetrKopyev commented on src/components/SideOrderMenu.vue
> +    orderButton() {
Изменил на if

2022-03-01 08:55 UTC, PetrKopyev commented on src/components/order/Model.vue
> +const cars = [
done

2022-03-02 08:15 UTC, e3Y6 requested changes
Добавлен комментарий.

2022-03-02 08:15 UTC, e3Y6 commented on src/components/Stages.vue
> +      :key="stepIndex"
Нужно поменять имя параметра. У объектов нет индексов.

2022-03-02 18:21 UTC, merged