Реализация V4/V5/V6/F2
PetrKopyev/simbirsoft-practice pull request #5
Opened 2022-03-02 18:22 UTC by PetrKopyev

2022-03-05 09:32 UTC, e3Y6 requested changes
Добавлены комментарии.

2022-03-05 09:32 UTC, e3Y6 commented on src/components/SideOrderMenu.vue
> +        'side-order-menu__button',
Для этого класса не нужна динамическая привязка. Лучше вынести в простой атрибут.

2022-03-05 09:32 UTC, e3Y6 commented on src/components/SideOrderMenu.vue
> +          'side-order-menu__button--active': selectedStep.filled || selectedStep.code === 'result',
`selectedStep.filled || selectedStep.code === 'result'` лучше вынести в `<script>`.

2022-03-05 09:32 UTC, e3Y6 commented on src/components/SideOrderMenu.vue
> +      if (this.selectedStep.code === 'location' || this.selectedStep.code === 'model' || this.selectedStep.code === 'options') {
`this.selectedStep.code === 'location' || this.selectedStep.code === 'model' || this.selectedStep.code === 'options'` лучше обозначить в отдельном выражении.

2022-03-05 09:32 UTC, e3Y6 commented on src/components/order/Info.vue
> +        alt=""
Лучше добавить текст.

2022-03-09 09:16 UTC, PetrKopyev commented on src/components/SideOrderMenu.vue
> +        'side-order-menu__button',
done

2022-03-09 09:19 UTC, PetrKopyev commented on src/components/SideOrderMenu.vue
> +          'side-order-menu__button--active': selectedStep.filled || selectedStep.code === 'result',
done

2022-03-09 09:26 UTC, PetrKopyev commented on src/components/SideOrderMenu.vue
> +      if (this.selectedStep.code === 'location' || this.selectedStep.code === 'model' || this.selectedStep.code === 'options') {
done

2022-03-09 09:27 UTC, PetrKopyev commented on src/components/order/Info.vue
> +        alt=""
done

2022-03-09 14:15 UTC, e3Y6 approved these changes

2022-03-10 15:18 UTC, merged